### ISSUE TITLE
Show current label/model statistics on the UI

### ISSUE THREAD

**Issue by sujen1412** [memex-explorer/sce-domain-discovery#10]
The UI should show the user the current number of pages labelled and the numberof pages in each label and the urls in those labels.

**Comment by wmburke** [comment]
You can make this work by just showing the number of highly relevant, relevant, and not relevant pages in the upper right corner of the page.

I don't think we need a total number marked, although a hover tip over all of these that says, "Mark at least 10 of each in order to build a good model. In this case, more is even better."

clicking on any of those should load all of that pages that have been marked with that relevancy - this should be the normal page, allowing them to re-mark the pages if necessary

Wayne Moses Burke, MS
Cognizant Engineer
Instrument Software and Science Data Systems Section (398)
NASA Jet Propulsion Laboratory Pasadena, CA 91109 USA
Mailstop: 168-527
E-mail: Wayne.M.Burke@jpl.nasa.gov<mailto:Wayne.M.Burke@jpl.nasa.gov>

On 06/20/2017 09:27 PM, Sujen Shah wrote:

The UI should show the user the current number of pages labelled and the numberof pages in each label and the urls in those labels.

**Comment by giuseppetotaro** [comment]
This is a preview of the new page showing the model statistics. @wmburke and @sujen1412, please comment it by summarizing all your suggestions.

<img width="1680" alt="screen shot 2017-06-22 at 11 55 27 am" src="https://user-images.githubusercontent.com/8323664/27451387-b482bf6c-5743-11e7-9b4a-130cc3f24e3b.png">

**Comment by wmburke** [comment]
Giuseppe, it looks nice. I would suggest you do the following:
1. Move Update Model back to the far right of the page.
2. Center align the "metrics" in the middle of the page.
3. Add the heart, check, and x icons by the metrics, including the colored circles that surround them and change the text to hovertips: "Highly Relevant" "Relevant" "Not Relevant".
4. Put a question mark in a dark blue circle (aka, a help icon) next to them that has a hovertip that reads the following: "For best results, you should mark at least 10 of each!"

**Comment by giuseppetotaro** [comment]
Closed by issue e6083eead105cc132f96b3f395bc0dc2a1511600.
The metrics related to the model (i.e., number of highly relevant results, number of relevant results, and number of non relevant results) are reported in the center of the header.
<img width="1680" alt="screen shot 2017-06-22 at 11 21 22 pm" src="https://user-images.githubusercontent.com/8323664/27472444-32ebf294-57b0-11e7-880d-3d99e785cec3.png">

**Comment by wmburke** [comment]
@giuseppe - this looks great, but please make a few minor tweaks if you can:

1. Instead of the ? at the end, put the hovertip over some intro text:
"You've marked: "

2. Push the metrics together so there isn't so much space between them:
there should be the equivalent of one space (&nbsp) between each one.

So the metrics should look like this (still centered):

You've marked: 2 O 5 O 5 O

(where the Os represent the icons)

Call if it doesn't make sense. Thanks.

**Comment by giuseppe** [comment]
I think @giuseppetotaro is the correct Giuseppe to tag :)

**Comment by wmburke** [comment]
Sorry @giuseppe - thanks for the correction.

**Comment by giuseppetotaro** [comment]
This is a preview.
<img width="1680" alt="screen shot 2017-06-23 at 9 30 07 am" src="https://user-images.githubusercontent.com/8323664/27493606-28ee0df0-57ff-11e7-82c7-9f5d8ea1ccf7.png">

**Comment by giuseppetotaro** [comment]
Commit 5673b1e0a7fe7028d62c4f1dd2cb1f36bedbe32b fixes the header based on the feedback. @wmburke please close this issue if it works for you.

**Comment by wmburke** [comment]
BOOM!
