### ISSUE TITLE
Have the results be marked as non -relevant by default

### ISSUE THREAD

**Issue by sujen1412** [memex-explorer/sce-domain-discovery#11]
The user is getting confused with the meaning of non-relevant, provide a way to mark all by default as non relevant and ask the user to only click the ones that are interesting. This may reduce the number of labels we have to two

**Comment by wmburke** [comment]
What is this based on? I would certainly argue that this is low priority at a minimum.

Wayne Moses Burke, MS
Cognizant Engineer
Instrument Software and Science Data Systems Section (398)
NASA Jet Propulsion Laboratory Pasadena, CA 91109 USA
Mailstop: 168-527
E-mail: Wayne.M.Burke@jpl.nasa.gov<mailto:Wayne.M.Burke@jpl.nasa.gov>

On 06/20/2017 09:27 PM, Sujen Shah wrote:

The user is getting confused with the meaning of non-relevant, provide a way to mark all by default as non relevant and ask the user to only click the ones that are interesting. This may reduce the number of labels we have to two

**Comment by giuseppetotaro** [comment]
@wmburke This allows to mark all the results as not relevant by default so that users do not have to mark all the results after the first search but only those that are relevant. Because the user is getting confused in distinguishing between high relevant and relevant, we could provide only two options: relevant and not relevant. Does it make sense?

**Comment by giuseppetotaro** [comment]
Closed by issue e6083eead105cc132f96b3f395bc0dc2a1511600.
After the first search, all the results are marked as non-relevant by default.
